Angular. NgRx
aleksander1802/angular2023Q4 pull request #6
Opened 2023-11-20 14:05 UTC by aleksander1802

1. Task: [Link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/angular/NgRX.md)
2. Screenshot: ![localhost_4200_youtube (2)](https://github.com/aleksander1802/angular2023Q4/assets/85034864/10fd7d91-154d-4f87-aaa1-0bb2a6602f79)
3. Deploy: [Link]
4. Done: 20.11.2023 / Deadline: 21.11.2023
5. Score: 100 / 100

# Scoring: Angular. NgRx

- [x] _Admin Page_ is generated (**+5**)
- [x] _Favorite Page_ is generated (**+5**)
- [x] NgRx package is used and storage is created (**+5**)
- [x] _Custom Cards_ are saved in the store (**+10**)
- [x] Videos (with _favorite button_) from the YouTube API received via Effects are saved in store (**+20**)
- [x] _Custom Cards_ (without _favorite button_) are displayed on _List Page_ combined with YouTube videos (**+20**)
- [x] _Favorite Page_ displays all marked videos from _List Page_ or _View Page_ (**+10**)
- [x] Clicking the _favorite button_ on the card on _Favorite Page_ removes item from the store and from the page
      immediately (**+15**)
- [x] _List Page_ displays 20 items with pagination and _Custom Cards_ are added to the beginning of the list on 1
      page (**+10**)

2023-12-03 01:18 UTC, ShkrobNastya requested changes

2023-12-03 01:18 UTC, ShkrobNastya commented on src/app/favorite/components/favorite-item/favorite-item.component.html
this component looks similar to app-search-item. Can we reuse app-search-item for favourite page?

2023-12-03 01:18 UTC, ShkrobNastya commented on src/app/youtube/components/pagination/pagination.component.ts
> +            localStorage.setItem('currentPage', this.currentPage.toString());
**you don't need to fix it** 
in future would be better to save current page in url params, not in localStorage (if you want to save page view after pagereload)

2023-12-03 01:18 UTC, ShkrobNastya commented on src/app/store/effects/video-cards.effects.ts
> +        ))
**you don't need to fix it**
as I see, getNextPage, getPrevPage looks similar: effects, reducers
I think the logic can be combined

2023-12-03 10:08 UTC, aleksander1802 commented on src/app/favorite/components/favorite-item/favorite-item.component.html
You're right, there is a similarity between `app-favorite-item` and `app-search-item`. To promote code reuse and maintainability, I'll explore the possibility of refactoring and reusing `app-search-item` in the `FavoriteModule`. I'll make sure to maintain the necessary functionality while consolidating common components. Thanks again for pointing this out!

2023-12-03 10:10 UTC, aleksander1802 commented on src/app/youtube/components/pagination/pagination.component.ts
> +            localStorage.setItem('currentPage', this.currentPage.toString());
It's a great idea, I agree 100% that it's much more convenient this way.

2023-12-03 19:01 UTC, ShkrobNastya approved these changes

2023-12-21 12:00 UTC, aleksander1802 commented on src/app/favorite/components/favorite-item/favorite-item.component.html
The fix is ready. Made the item-search component global. So I'm reusing it in Search Results and in Favorite Results. Thus, the unused favorite item component had to be deleted.

2024-01-23 12:00 UTC, merged